# Generated by Django 4.1.2 on 2022-10-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pelicula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=50)),
                ("director", models.CharField(max_length=50)),
                ("image", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
            ],
        ),
    ]
